### ISSUE TITLE
Добавить для документов поле "Название"

### ISSUE THREAD

**Issue by VictorPozdeev1** [Toolll1/document-flow#88]
**Is your feature request related to a problem? Please describe.**
Мне как пользователю хотелось бы видеть названия для моих документов, которые я задаю сам - чтоб проще их идентифицировать.

**Describe the solution you'd like**
Добавить поле "Название" (вероятно, без требования уникальности).
Сейчас поле "Название" тоже есть, но оно генерируется сервером и для пользователя оно не очень удобно.
Но его нужно тоже оставить, вероятно - т.к. сейчас оно используется для генерации имени файла.

**Comment by FokiDoki** [comment]
Закинули в бэклок, спасибо
