### ISSUE TITLE
Синхронизировать спецификацию OpenAPI с реальными контрактами эндпойнтов

### ISSUE THREAD

**Issue by VictorPozdeev1** [Toolll1/document-flow#89]
Мы подключили в проект кодогенерацию по спецификации OpenAPI. Планируем при выпуске релиза 2.0. просто перезапустить её.
Но уже сейчас иногда встречаются несовпадения, которые приходится править руками.
Большая к вам просьба - поддерживать спецификацию в актуальном состоянии, когда вносятся изменения.
В комментах к этой ишшью мы планируем писать конкретные случаи несовпадения, которые есть сейчас и которые будут нам встречаться.

**Comment by FokiDoki** [comment]
Закрыто из-за неактивности

**Comment by VictorPozdeev1** [comment]
После того как вы добавили возврат данных о пользователе при логине, вы в сваггер это не включили. В релизе 2.0 будет?
У нас сейчас вот такой файл есть в проекте:
```
/* Этот файл был создан вручную, уже после того как основная масса сгенерирована автоматически (т.к. бэкенд теперь присылает UserDto в ответе) */

/* eslint-disable */
export type CurrentUserData = {
  dateOfBirth: string;
  email: string;
  firstName: string;
  lastName: string;
  organizationId: number;
  patronymic: string;
  phone: string;
  post: string;
  role: string;
};

export type UserLoginResponseDto = {
  token: string;
  user: CurrentUserData;
};

```

**Comment by VictorPozdeev1** [comment]
По урлу /document сейчас в сваггере описана схема такая:
```
[
  {
    "ID документа": 0,
    "name": "string",
    "documentPath": "string",
    "date": "2023-12-30T09:09:52.528Z",
    "idOrganization": 0,
    "ownerId": 0,
    "docTypeName": "string",
    "attributeValues": [
      {
        "valueId": 0,
        "value": "string",
        "attribute": {
          "id": 0,
          "name": "string",
          "type": "string"
        }
      }
    ],
    "finalDocStatus": "string"
  }
]
```
На самом деле, возвращается не "ID документа", а просто "id". И это лучше, конечно.
Нужно обновить спецификацию в сваггере..

**Comment by FokiDoki** [comment]
> После того как вы добавили возврат данных о пользователе при логине, вы в сваггер это не включили. В релизе 2.0 будет? У нас сейчас вот такой файл есть в проекте:
> 
> ```
> /* Этот файл был создан вручную, уже после того как основная масса сгенерирована автоматически (т.к. бэкенд теперь присылает UserDto в ответе) */
> 
> /* eslint-disable */
> export type CurrentUserData = {
>   dateOfBirth: string;
>   email: string;
>   firstName: string;
>   lastName: string;
>   organizationId: number;
>   patronymic: string;
>   phone: string;
>   post: string;
>   role: string;
> };
> 
> export type UserLoginResponseDto = {
>   token: string;
>   user: CurrentUserData;
> };
> ```

Пофиксили, в версии 2.0 будет в порядке

**Comment by FokiDoki** [comment]
> По урлу /document сейчас в сваггере описана схема такая:
> 
> ```
> [
>   {
>     "ID документа": 0,
>     "name": "string",
>     "documentPath": "string",
>     "date": "2023-12-30T09:09:52.528Z",
>     "idOrganization": 0,
>     "ownerId": 0,
>     "docTypeName": "string",
>     "attributeValues": [
>       {
>         "valueId": 0,
>         "value": "string",
>         "attribute": {
>           "id": 0,
>           "name": "string",
>           "type": "string"
>         }
>       }
>     ],
>     "finalDocStatus": "string"
>   }
> ]
> ```
> 
> На самом деле, возвращается не "ID документа", а просто "id". И это лучше, конечно. Нужно обновить спецификацию в сваггере..

пофикшено в версии 2.0
